# Generated by Django 2.2.13 on 2020-06-30 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 7, 0, 43, 31719, tzinfo=utc), null=True),
        ),
    ]
