# Generated by Django 2.2.13 on 2020-06-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200630_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
