# Generated by Django 2.2.13 on 2020-07-01 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200630_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 5, 50, 8, 633603, tzinfo=utc)),
        ),
    ]
